import { ArrowLeft, LoaderCircle, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Logo } from '@/components/Logo'
import { Button } from '@/components/ui/button'

export function AuthShell({ children, title, description, footer, aside }) {
  return <main className="min-h-screen bg-canvas lg:grid lg:grid-cols-[minmax(0,0.95fr)_minmax(460px,1.05fr)]"><section className="relative hidden overflow-hidden bg-ink px-10 py-10 text-white lg:flex lg:flex-col xl:px-16"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: 'linear-gradient(rgba(125, 211, 252, .08) 1px, transparent 1px), linear-gradient(90deg, rgba(125, 211, 252, .08) 1px, transparent 1px)', backgroundSize: '48px 48px' }} /><div className="absolute -right-28 top-20 h-80 w-80 rounded-full bg-primary/20 blur-3xl" /><div className="absolute -bottom-20 left-10 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl" /><Logo light className="relative z-10" /><div className="relative z-10 my-auto max-w-lg py-20"><div className="mb-8 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-xs font-semibold text-cyan-200"><Sparkles className="h-3.5 w-3.5" /> A clearer way to choose your next move</div><h1 className="font-display text-5xl font-semibold leading-[1.04] tracking-[-0.06em] xl:text-6xl">Your CV is more than a document.</h1><p className="mt-6 max-w-md text-base leading-7 text-slate-300">Turn scattered experience into a confident story, then see where it could take you next.</p><div className="mt-12 grid max-w-sm grid-cols-2 gap-6 border-t border-white/10 pt-6"><div><p className="font-display text-2xl font-semibold">Explainable</p><p className="mt-1 text-xs leading-5 text-slate-400">See the signal behind every score.</p></div><div><p className="font-display text-2xl font-semibold">Private</p><p className="mt-1 text-xs leading-5 text-slate-400">Your documents belong to you.</p></div></div></div><p className="relative z-10 text-xs text-slate-500">CVision AI · Career intelligence workspace</p></section><section className="flex min-h-screen flex-col px-5 py-6 sm:px-10 lg:px-16 xl:px-24"><div className="flex items-center justify-between lg:hidden"><Logo /><Button variant="ghost" size="sm" asChild><Link to="/"><ArrowLeft className="h-4 w-4" /> Home</Link></Button></div><div className="mx-auto flex w-full max-w-md flex-1 flex-col justify-center py-12"><div className="mb-8">{title && <h2 className="font-display text-3xl font-semibold tracking-[-0.05em] text-foreground">{title}</h2>}{description && <p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p>}</div>{children}</div>{footer && <div className="mx-auto w-full max-w-md">{footer}</div>}{aside}</section></main>
}

export function AuthAside() {
  return <div className="mx-auto mb-8 mt-8 w-full max-w-md rounded-2xl border border-border bg-card p-4 shadow-card"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Built for better conversations</p><p className="mt-2 text-sm leading-6 text-foreground/80">Upload a CV, understand the gaps, and walk into your next application with a point of view.</p></div>
}

export function AuthSpinner() {
  return <LoaderCircle className="h-4 w-4 animate-spin" aria-hidden="true" />
}
