import { BriefcaseBusiness, CalendarDays } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { safeArray } from '@/lib/utils'

export function ExperienceTimeline({ experience = [] }) {
  const items = safeArray(experience)
  if (!items.length) return <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No structured experience was returned for this CV.</div>
  return <div className="relative space-y-0">{items.map((item, index) => <div key={`${item?.company || 'role'}-${item?.title || index}`} className="relative grid grid-cols-[88px_20px_minmax(0,1fr)] gap-4 pb-8 last:pb-0"><div className="pt-0.5 text-right text-xs font-medium text-muted-foreground">{item?.startDate || item?.startYear || item?.date || '—'}{item?.endDate || item?.endYear ? <><br /><span className="text-muted-foreground/70">to {item?.endDate || item?.endYear}</span></> : null}</div><div className="relative flex justify-center"><span className="z-10 mt-1.5 h-3 w-3 rounded-full border-2 border-primary bg-canvas ring-4 ring-primary/10" />{index < items.length - 1 && <span className="absolute top-5 h-full w-px bg-border" />}</div><Card className="p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><BriefcaseBusiness className="h-4 w-4" /></span><div className="min-w-0"><h3 className="font-semibold text-foreground">{item?.title || item?.position || item?.role || 'Experience'}</h3><p className="mt-0.5 text-sm text-muted-foreground">{item?.company || item?.organization || 'Company not specified'}</p>{item?.location && <p className="mt-2 flex items-center gap-1.5 text-xs text-muted-foreground"><CalendarDays className="h-3.5 w-3.5" /> {item.location}</p>}{item?.description && <p className="mt-3 text-sm leading-6 text-foreground/75">{item.description}</p>}{item?.highlights && <ul className="mt-3 space-y-1.5 text-sm text-foreground/75">{safeArray(item.highlights).map((highlight) => <li key={highlight} className="flex gap-2"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary" />{highlight}</li>)}</ul>}</div></div></Card></div>)}</div>
}
